server:
  port: 7777
  servlet:
    context-path: /NoOps-DB

#logging:
#  level:
#    org.springframework.security: trace

NoOpsDB:
  cached-path: DbSource.db
  admin-password: admin123
  guest-password: guest123
